### ISSUE TITLE
IDSConnector is removed from the list of connectors after being connected for while

### ISSUE THREAD

**Issue by edgardmarx** [International-Data-Spaces-Association/metadata-broker-open-core#32]
**Describe the bug**
IDSConnector is removed from the list of connectors after being connected for while.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect with the IDSConnector in a Brocker (https://broker.mobilitydataspace.io/) 
2. It will be listed in connector area (https://broker.mobilitydataspace.io/connector)
2. Wait a while (1 day)
3. The resource published is still being listed in resource tab (https://broker.mobilitydataspace.io/resources, i.e see image attached), but the broker not (see image attached)

**Expected behaviour**
Both, the resource and the connector should be listed.

**Screenshots**
screenshot_1 -> Broker connected
screenshot_2 -> Console log, confirmation Broker is connected
screenshot_3 -> Broker not being listed anymore 
screenshot_4 -> Resource still being listed

![Screenshot_1](https://user-images.githubusercontent.com/4638593/120167030-8c51f480-c1fd-11eb-8d69-5713bfe120d9.png)
![Screenshot_2](https://user-images.githubusercontent.com/4638593/120167033-8cea8b00-c1fd-11eb-961e-f9ec68f38f83.png)
![Screenshot_3](https://user-images.githubusercontent.com/4638593/120167061-9673f300-c1fd-11eb-91f4-8f847cd41dd7.png)
![Screenshot_4](https://user-images.githubusercontent.com/4638593/120167027-8bb95e00-c1fd-11eb-87ec-eb9ac99d16c0.png)

**Additional context**
I am connecting to the broker.mobilitydataspace.io using Broker version 4.3.1 and inbound and outbound models 4.0.0

**Comment by maboeckmann** [comment]
Dear @edgardmarx ,
yesterday, I have made some small changes to make the re-indexing mentioned by @sebbader more robust. The code changes will be reflected on the central broker instance of the IDS Lab on Tuesday. The mobility data space broker will most probably have its own update cycle and I would need to point you to @sebplorenz who maintains this deployment. Should your connector disappear from the indexing even after the  redeployment, I would kindly ask you to send me an email with a self-description of your connector, so that I can dig deeper.
